// <auto-generated />
using System;
using FirebirdApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirebirdApi.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20250911194148_AddMachineIdToLocalNode")]
    partial class AddMachineIdToLocalNode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("FirebirdApi.Models.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StoredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_email");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("auth_tokens");
                });

            modelBuilder.Entity("FirebirdApi.Models.DatabaseConfigSqlite", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Charset")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("charset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("database_path");

                    b.Property<string>("DesktopNodeId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("desktop_node_id");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("LastSizeCheck")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_size_check");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("server");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDefault");

                    b.ToTable("database_configs");
                });

            modelBuilder.Entity("FirebirdApi.Models.DatabaseSnapshotSqlite", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("CurrentTable")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_table");

                    b.Property<string>("DatabaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("database_id");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("database_name");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("EstimatedCompletion")
                        .HasColumnType("TEXT")
                        .HasColumnName("estimated_completion");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int>("ProcessedTables")
                        .HasColumnType("INTEGER")
                        .HasColumnName("processed_tables");

                    b.Property<decimal>("ProgressPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("progress_percentage");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_data");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TotalTables")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_tables");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseId");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("Status");

                    b.ToTable("database_snapshots");
                });

            modelBuilder.Entity("FirebirdApi.Models.LocalNode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AnonymousExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("anonymous_expires_at");

                    b.Property<string>("AnonymousToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("anonymous_token");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("architecture");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_anonymous");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_name");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("operating_system");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<string>("SystemVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("system_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsAnonymous");

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.HasIndex("MachineName");

                    b.HasIndex("UserId");

                    b.ToTable("local_nodes");
                });

            modelBuilder.Entity("FirebirdApi.Models.ProjectSettingsSqlite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DefaultDatabaseId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_database_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("project_settings");
                });

            modelBuilder.Entity("FirebirdApi.Models.SnapshotCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_key");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cached_at");

                    b.Property<string>("CachedData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cached_data");

                    b.Property<string>("DatabaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("database_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("DatabaseId", "CacheKey")
                        .IsUnique();

                    b.ToTable("snapshot_cache");
                });

            modelBuilder.Entity("FirebirdApi.Models.SnapshotTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at");

                    b.Property<long?>("LastId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_id");

                    b.Property<long>("RecordCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_count");

                    b.Property<string>("Schema")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_name");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("table_name");

                    b.Property<string>("TableType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("table_type");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("SnapshotId", "TableName");

                    b.ToTable("snapshot_tables");
                });

            modelBuilder.Entity("FirebirdApi.Models.SnapshotTableColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("column_name");

                    b.Property<string>("DataType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_nullable");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary_key");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length");

                    b.Property<int?>("Precision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("precision");

                    b.Property<int?>("Scale")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scale");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("table_name");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("SnapshotId", "TableName");

                    b.ToTable("snapshot_table_columns");
                });
#pragma warning restore 612, 618
        }
    }
}
