# 
# List of known database aliases 
# ------------------------------ 
# 
# Examples: 
# 
#   dummy = c:\data\dummy.fdb 
#  
# Alias para o banco TAVAGUA
TAVAGUA = C:\Projetos\estudos\forti\dash\dbs\TAVAGUA.FDB
